spring.application.name=movie_management

spring.datasource.url=jdbc:mysql://localhost:3306/movie_db
spring.datasource.username=root
spring.datasource.password=Dkpho@9t
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
